trigger:
- main
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.x' # ou '7.x', '6.x' selon votre version

steps:
- task: UseDotNet@2
  displayName: 'Installer .NET SDK'
  inputs:
    version: '$(dotnetVersion)'
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  displayName: 'Restaurer les packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build du projet'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Ex√©cuter les tests'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publier le projet'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish --no-build --no-restore'

- task: PublishBuildArtifacts@1
  displayName: 'Publier les artefacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'